### ISSUE TITLE
JDI framework doesn’t get "healdess" parameter from test.properties

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#19]
JDI framework doesn’t get "healdess" parameter from test.properties.
Framework gets "healdess" parameter from common.properties and from *driver name*.properties.
**Expected:** possible to set the parameter in test.properties.
**Actual:** parameter in test.properties is ignored.
![headless](https://user-images.githubusercontent.com/56273100/211320839-25119aae-f4c2-4443-9f4e-1eb1f98307b2.png)
Also there's no description how this parameter works on https://jdi-docs.github.io/jdi-light/. Would be nice to add.
![headless_2](https://user-images.githubusercontent.com/56273100/211321060-a6cb428d-8eef-4b79-b6e7-6b4c2d9ffa57.png)

**Comment by pnatashap** [comment]
Thank you for the issue. 
Actually this parameter is used by the framework, but it can be overriden by https://github.com/jdi-templates/jdi-light-testng-template/blob/master/src/test/resources/common.properties 
(We do not parse that parameters, paste them as is to browser run)
