### ISSUE TITLE
Some of JDI Framework methods are hard to read. Variables names do not comply with the Java Naming Convention.

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#20]
Some of JDI Framework methods are hard to read. Variables names do not comply with the Java Naming Convention.
![variables naming](https://user-images.githubusercontent.com/56273100/211322087-119bbff3-1f20-43a6-a0a8-8ddfd8125155.png)

**Comment by pnatashap** [comment]
Thank for the issue.
The code you see is IDE decompilation. And this code is a result of AspectJ library, there is no handwritten code for that injection.
Original code for that class is in https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-core/src/main/java/com/epam/jdi/light/elements/composite/WebPage.java
