### ISSUE TITLE
Public modifier should be deleted in TestsInit interface’s methods

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#21]
Public modifier should be deleted in TestsInit interface’s methods.
Default methods are implicitly public, there's no need to specify the public modifier.

![publicDefault](https://user-images.githubusercontent.com/56273100/211322565-4dbdf76e-fa69-4029-a37d-b5cf15d9258d.png)

**Comment by pnatashap** [comment]
fixed
