### ISSUE TITLE
TestNG.xml (general.xml) file doesn’t find test classes because it searches in “packages”, not in classes

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#22]
TestNG.xml (In this repository it named general.xml) file doesn’t find test classes because it searches in “packages”, not in classes.
Here's how to fix it:
![packagesClasses](https://user-images.githubusercontent.com/56273100/211322944-4f828591-f9ac-4052-bf61-7ad6e5bd48fa.png)

**Comment by pnatashap** [comment]
Thank for the issue.
In our file [src/test/resources/general.xml](https://github.com/jdi-templates/jdi-light-testng-template/blob/master/src/test/resources/general.xml) we use package name org.mytests.tests.example (without class name) 
If you need to run another class, you can change that file for your purposes
