### ISSUE TITLE
Only a suggestion. Maybe it'll be good to move strings like "FAILED", "PASSED", "ERROR: ", etc. to separate static final String variables

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#23]
Maybe it'll be good to move next strings:
"PASSED", 
"FAILED", 
"SKIPPED",
"ERROR: ", 
"UNKNOWN ERROR"
to separate static final String variables
![variables java](https://user-images.githubusercontent.com/56273100/211513116-fd2300d3-b48d-4f31-ba77-9afa603608dd.png)

**Comment by pnatashap** [comment]
@sergei820 you can create a PR in this repo to change it. 
This is demo class for logging results, can not be used
