### ISSUE TITLE
screenshots doesn't attach to Allure report if jdiAssert fails test scenario

### ISSUE THREAD

**Issue by sergei820** [jdi-templates/jdi-light-testng-template#24]
jdiAssert fails test scenario, but doesn't fail test step, 
that's why there's no attached screenshots in steps, failed by jdiAssert and there is in steps, failed by UIElement.is() asserts.
(discovered while researching screenshot attachment trouble)

**Comment by pnatashap** [comment]
Thank you for your issue.
Unfortunately I can not reproduce your bug. 
The steps needed to follow to check allure report:

- install allure as described https://docs.qameta.io/allure/#_get_started
- run tests
- go to the folder target/allure-results
- run command `allure serve .`

I change the test: 
`@Test
    public void commonMatchersTest() {
        users.is().displayed();
        users.has().size(5); // the error is expected here
        users.assertThat().size(greaterThan(3));
        users.is().notEmpty().size(lessThanOrEqualTo(6));
    }`

and I can see the image in the report.

@sergei820  If you still have the same issue, please attach some code to be able to check what are you talking about.
