### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by jreznot** [jdi-templates/jdi-light-testng-template#4]
The example seems outdated and does not compile
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-light-testng-template: Compilation failure
[ERROR] /home/artamonov/test/qa/jdi-light-testng-template/src/main/java/org/mytests/uiobjects/example/site/custom/MultiDropdown.java:[26,47] type argument com.epam.jdi.light.asserts.generic.UISelectAssert is not within bounds of type-variable A
```

Warning in IDE:
![image](https://user-images.githubusercontent.com/1066152/81000592-2dca1380-8e4f-11ea-828d-ce98f82f5220.png)

**Comment by pnatashap** [comment]
@jreznot  could you please recheck this project.
It was updated to current jdi version and checked on all jdk on ubuntu.
please close the issue if it's ok now, or provide more information about jdk and os.

**Comment by pnatashap** [comment]
No response. Now we add automatic runs to check the code in the project, it should work
