### ISSUE TITLE
Template test run is not successfull

### ISSUE THREAD

**Issue by mamkinalozhka** [jdi-templates/jdi-light-testng-template#7]
Exactly like in [the build logs on travis](https://travis-ci.com/github/jdi-templates/jdi-light-testng-template/jobs/380720742), I receive an
 `java.lang.RuntimeException: 
  java.lang.RuntimeException: 
Failed to do screenshot. No Drivers run
Caused by: java.lang.RuntimeException: 
Failed to do screenshot. No Drivers run`
exception after running the command `mvn install`/`mvn clean install` or while running a test in the IDE (eclipse) with TestNG Plugin.

Could you please fix this issue or at least explain, what should a beginner user do to make test run successful?

**Comment by RomanIovlev** [comment]
Please update your Chrome browser to the latest version. This issue caused by different versions of the latest driver and your browser
